import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir } from 'node:fs/promises';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const pluginId = 'obsidian-book-info-plugin';
const buildDir = `build_output/${pluginId}`;
const outfile = prod ? `${buildDir}/main.js` : 'main.js';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile,
	minify: prod,
});

if (prod) {
	await mkdir(buildDir, { recursive: true });
	await context.rebuild();
	await Promise.all([
		copyFile('manifest.json', `${buildDir}/manifest.json`),
		copyFile('styles.css', `${buildDir}/styles.css`),
		copyFile('default-book-template.md', `${buildDir}/default-book-template.md`),
	]);
	process.exit(0);
} else {
	await context.watch();
}
